### ISSUE TITLE
Додавання магазину

### ISSUE THREAD

**Issue by RolandE36** [nromanen/Ch-044#20]
Назва, адреса, логотип.

**Comment by alisaanosova** [comment]
Що поправити?

**Comment by RolandE36** [comment]
1. Імена файлів не унікальні.
2. Після додавання магазину перейти на сторінку з списком
3. Зробити на всю ширину список.
4. Зробити ще редагування магазину.
5. Зробити видалення. Але не видаляти з БД, тільки статус міняти. І це діалогом, не сторінкою.
6. Переклад.
