### ISSUE TITLE
Tor.net modify user agent

### ISSUE THREAD

**Issue by RolandE36** [nromanen/Ch-044#39]
Спробуват змітини юзер агент стрічку для тора. 
Зробити щоб він при кожному запиті рандомно підставляв юзер анегт віж хрома чи фаєрфокса.
Це повинно пофіксати проблему з капчою на сайтах.

**Comment by StasYakhnenko** [comment]
не фіксає проблему з капчою
певні сайти використовують сервіс https://www.cloudflare.com/ ,який по суті являється "охоронцем" сайту. й там вже блокується трафік тору
читай подробніше тут:
https://blog.torproject.org/blog/trouble-cloudflare

**Comment by StasYakhnenko** [comment]
![image](https://cloud.githubusercontent.com/assets/22484244/20674768/c3978abc-b592-11e6-8b69-caf146ae026d.png)

й використовується саме така капча, що не дозволяє надсилати на емейл текст капчі

**Comment by RolandE36** [comment]
Добре, тоді додай можливість вибрати юзати чи не юзати Тор. Тільки не роби це чекбоксом. Нехай то буде випадаючий список з двома значеннями "дефолт конекшин" і "тор". (просто якщо потім додамо ще якісь проксі сервери, то щоб не довелось діалог міняти)
