### ISSUE TITLE
Перевірка чи товар досі існує

### ISSUE THREAD

**Issue by RolandE36** [nromanen/Ch-044#47]
Якщо товар видалено, то треба маркнути його як видалений в БД.

Це має бути таск який перевірятиме існуючі товари в якійсь категорії в нашій БД з списком товарів в магазині.

**Comment by StasYakhnenko** [comment]
не фіксає проблему з капчою
певні сайти використовують сервіс https://www.cloudflare.com/ ,який по суті являється "охоронцем" сайту. й там вже блокується трафік тору
читай подробніше тут:
https://blog.torproject.org/blog/trouble-cloudflare

**Comment by StasYakhnenko** [comment]
роман, пару нюансів
це виходить метод має приймати айдішку категорії, по якій й будуть витягуватись товари, й також айдішка парсертаску, з якої тянеться юрлка, проходження по пейджам, й ікспаси до товарів?

**Comment by RolandE36** [comment]
Да.
